sonar.projectKey=najmulhasan_Electrical-Work-Singapore
sonar.projectName=Electrical Works Singapore
sonar.projectVersion=1.0.0
sonar.organization=najmulhasan

# Sources
sonar.sources=src
sonar.exclusions=node_modules/**,**/*.test.ts,**/*.test.tsx,.next/**

# Tests
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Code Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Language
sonar.language=ts
sonar.sourceEncoding=UTF-8
